### ISSUE TITLE
Suggested packages confirmation

### ISSUE THREAD

**Issue by LinusSkucas** [MycroftAI/mycroft-skills-manager#41]
When I install a skill that installs apt packages through a `manifest.yml`, if those packages have suggested packages I am asked to confirm those packages (by pressing enter). on packages without suggested packages, I am not asked to confirm

**Comment by krisgesling** [comment]
Hey Linus, have you got an example of each I can take a look at?

**Comment by LinusSkucas** [comment]
Hey @krisgesling sorry for not getting back to you for awhile.
Here's my manifest.yml:
```yaml
dependencies:
  python:
    - vobject
    - ics
    - caldav
    - pyyaml

  system:
    all: libxml2-dev libxslt-dev python-dev python3-lxml
```
